[tox]
envlist = py3
requires =
    tox-uv

[pytest]
addopts =
    --cov=resultsdb_frontend
    --cov-report=term-missing
    --cov-report=xml

[coverage:run]
branch = true
source_pkgs =
    resultsdb_frontend

[coverage:paths]
source =
    resultsdb_frontend/
    .tox/py3/lib/python*/site-packages/resultsdb_frontend/

[testenv]
basepython = python3.14
runner = uv-venv-runner
deps =
    pytest
    pytest-cov
    -r requirements.txt
commands =
    pytest {posargs}
setenv =
    TEST = true
